import { useState, useContext } from "react";
import {
  Menu,
  LogOut,
  LayoutDashboard,
  User,
  Shield,
  MessageSquare,
} from "lucide-react";
import { motion } from "framer-motion";
import { Outlet, NavLink, useLocation } from "react-router-dom";
import AuthContext from "../../context/AuthContext";
import AuraBackground from "../../components/layout/AuraBackground";
import Footer from "../../components/layout/Footer";

export default function AthleteLayout() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const auth = useContext(AuthContext);
  const location = useLocation();

  if (!auth) return null;

  // 🚀 THE FIX: ALL routing logic/redirects have been deleted.
  // The layout simply acts as a visual wrapper now.

  const navItems = [
    { label: "Performance Hub", path: "/athlete", icon: LayoutDashboard },
    { label: "Personal Profile", path: "/athlete/profile", icon: User },
    {
      label: "Leave Review",
      path: "/athlete/leave-review",
      icon: MessageSquare,
    },
  ];

  const userProfileImage = (auth.user as unknown as { profileImage?: string })
    ?.profileImage;
  const isAutoGeneratedAvatar =
    userProfileImage?.includes("ui-avatars.com") ||
    userProfileImage?.includes("googleusercontent.com");
  const backgroundImageUrl = isAutoGeneratedAvatar
    ? undefined
    : userProfileImage;

  return (
    <div className="min-h-screen text-white flex font-sans selection:bg-amber-500/30 relative z-0">
      <AuraBackground imageUrl={backgroundImageUrl} />

      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/60 backdrop-blur-sm z-40 md:hidden transition-opacity duration-300"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      <aside
        className={`fixed z-50 inset-y-0 left-0 w-72 bg-black/20 backdrop-blur-2xl border-r border-white/5 shadow-[10px_0_30px_rgba(0,0,0,0.5)] transform transition-all duration-500 ease-in-out ${sidebarOpen ? "translate-x-0" : "-translate-x-full"} md:translate-x-0 md:static md:block`}
      >
        <div className="p-8 mb-4">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 bg-amber-500 rounded-xl flex items-center justify-center shadow-[0_0_20px_rgba(245,158,11,0.3)]">
              <span className="text-black font-black text-xl italic">AZ</span>
            </div>
            <div>
              <h2 className="text-sm font-black tracking-tighter uppercase italic leading-none">
                The Athletic Zone
              </h2>
            </div>
          </div>
        </div>

        <nav className="p-6 space-y-2">
          <p className="text-[10px] font-black uppercase tracking-[0.3em] text-white/20 mb-6 ml-3">
            Training Sectors
          </p>
          {navItems.map((item) => (
            <NavLink
              key={item.label}
              to={item.path}
              end={item.path === "/athlete"}
              onClick={() => setSidebarOpen(false)}
              className={({ isActive }) =>
                `group relative px-4 py-3 rounded-xl transition-all duration-300 flex items-center gap-3 overflow-hidden ${isActive ? "bg-white/[0.05] border border-white/10 text-white" : "hover:bg-white/[0.03] border border-transparent text-white/40"}`
              }
            >
              {({ isActive }) => (
                <>
                  <div
                    className={`absolute left-0 top-1/2 -translate-y-1/2 h-4 w-[2px] bg-amber-500 rounded-full transition-all duration-300 ${isActive ? "opacity-100" : "opacity-0"}`}
                  />
                  <item.icon
                    size={18}
                    className={
                      isActive ? "text-amber-500" : "group-hover:text-white/80"
                    }
                  />
                  <span
                    className={`text-[11px] font-black uppercase tracking-widest transition-colors ${isActive ? "text-amber-500" : ""}`}
                  >
                    {item.label}
                  </span>
                </>
              )}
            </NavLink>
          ))}
          <button
            type="button" // 🚀 FIX 1: Prevents default form submission behavior
            onClick={(e) => {
              e.preventDefault(); // 🚀 FIX 2: Stops the browser from interrupting the network request
              if (auth?.logout) {
                auth.logout(); // 🚀 FIX 3: Just call the function, it handles the redirect internally!
              }
            }}
            className="flex items-center gap-3 px-4 py-3 mt-12 text-red-500/40 hover:text-red-500 hover:bg-red-500/5 rounded-xl transition-all w-full text-[11px] font-black uppercase tracking-widest active:scale-95"
          >
            <LogOut size={18} /> Logout
          </button>
        </nav>
      </aside>

      <div className="flex-1 flex flex-col h-screen overflow-hidden bg-transparent">
        <header className="sticky top-0 w-full border-b border-white/5 bg-black/40 backdrop-blur-xl z-30 shadow-md">
          <div className="hidden md:flex items-center justify-between px-8 py-6">
            <div className="flex items-center gap-6">
              <div>
                <h1 className="text-xl font-black tracking-tighter uppercase italic leading-none drop-shadow-lg">
                  System <span className="text-amber-500">Active</span>
                </h1>
                <p className="text-[10px] font-bold text-white/50 uppercase tracking-widest mt-1">
                  Authorized Athlete: {auth.user?.name || "Unverified"}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2 px-4 py-1.5 text-[10px] font-black rounded-full bg-amber-500/10 text-amber-500 border border-amber-500/20 tracking-widest uppercase shadow-[0_0_15px_rgba(245,158,11,0.1)]">
                <Shield size={12} /> CLEARANCE: {auth.user?.role || "PENDING"}
              </div>
              <div className="w-10 h-10 rounded-xl bg-[#0B0F14] border border-amber-500/20 overflow-hidden flex items-center justify-center text-sm font-black text-amber-500 shadow-xl">
                {userProfileImage ? (
                  <img
                    src={userProfileImage}
                    alt="Avatar"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  auth.user?.name?.charAt(0).toUpperCase() || "A"
                )}
              </div>
            </div>
          </div>

          <div className="flex flex-col md:hidden px-4 py-3 gap-1">
            <div className="flex items-center justify-between">
              <button
                className="text-white/70 hover:text-white p-2 -ml-2 active:scale-95 transition-transform"
                onClick={() => setSidebarOpen(true)}
              >
                <Menu size={24} />
              </button>
              <h1 className="text-lg font-black tracking-tighter uppercase italic leading-none drop-shadow-lg">
                System <span className="text-amber-500">Active</span>
              </h1>
              <div className="w-9 h-9 rounded-xl bg-[#0B0F14] border border-amber-500/20 overflow-hidden flex items-center justify-center text-sm font-black text-amber-500 shadow-xl">
                {userProfileImage ? (
                  <img
                    src={userProfileImage}
                    alt="Avatar"
                    className="w-full h-full object-cover"
                  />
                ) : (
                  auth.user?.name?.charAt(0).toUpperCase() || "A"
                )}
              </div>
            </div>
          </div>
        </header>

        <main className="flex-1 overflow-y-auto relative p-4 md:p-12 pb-24 scroll-smooth">
          <motion.div
            key={location.pathname}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut" }}
            className="max-w-7xl mx-auto"
          >
            <Outlet />
          </motion.div>
          <Footer />
        </main>
      </div>
    </div>
  );
}
